# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e2b32e67e0fdbfcc309c945144975837c8a67b1f422b24d00c1ebeb3238a9fb57568582242b89cf5c0b96cf131ad1c9e2b4f57dd1b43e5376d8cf0200f320b3

test:
  secret_key_base: 089ae9519b28199cc0ca6e624e7b4a8740a037f63055f358147a2841fd311296a347ac54c328654ff47ab529e32f38ca301135059e24119c3fc1278ad2f98115

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
